In [43]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeRegressor

In [74]:
df_all = pd.read_csv('train.csv')

In [45]:
df_all.head()

,Скважина,Дата,Характер работы,Состояние,"Время работы, ч","Нефть, т","Вода, т","Жидкость, т","Попутный газ, м3","Закачка, м3",...,Р пл,Р заб расчётное,Потери давления на трение,Р затр,Р уст,Закачка за месяц,Рпл,k,Р уст.1,Р заб
0,101,01.12.2016,НЕФ,РАБ.,744,"186,44","241,84","428,28",7820,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,102,01.12.2016,НАГ,РАБ.,744,0,0,0,0,2096,...,258.0,436.472966,1.162974,195.0,196.0,2190.0,0.0,3.271276,196.0,430.412299
2,103,01.12.2016,НЕФ,РАБ.,744,"554,09","399,36","953,45",23241,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,104,01.12.2016,НЕФ,РАБ.,744,"225,65","351,29","576,94",9465,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,105,01.12.2016,НЕФ,РАБ.,744,"953,7","284,71","1238,41",40002,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [46]:
df_all[df_all['Характер работы'] == 'НЕФ'].head()

,Скважина,Дата,Характер работы,Состояние,"Время работы, ч","Нефть, т","Вода, т","Жидкость, т","Попутный газ, м3","Закачка, м3",...,Р пл,Р заб расчётное,Потери давления на трение,Р затр,Р уст,Закачка за месяц,Рпл,k,Р уст.1,Р заб
0,101,01.12.2016,НЕФ,РАБ.,744,"186,44","241,84","428,28",7820,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,103,01.12.2016,НЕФ,РАБ.,744,"554,09","399,36","953,45",23241,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,104,01.12.2016,НЕФ,РАБ.,744,"225,65","351,29","576,94",9465,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,105,01.12.2016,НЕФ,РАБ.,744,"953,7","284,71","1238,41",40002,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,107,01.12.2016,НЕФ,РАБ.,744,"701,56","205,1","906,66",29426,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
# df_all[df_all['Характер работы'] == 'НЕФ'][['Скважина', 
#                                             'Дата',
#                                             'Время работы ч ',
#                                             'Обводненность (вес), %',
#                                             'Тип скважены',
#                                             'Диаметр НКТ',
#                                             'Диаметр штуцера'
#                                            ]]

In [55]:
len(df_all[df_all['Характер работы'] == 'НЕФ']['Скважина'].unique())

267

In [50]:
df_coords = pd.read_csv('coords.csv')

In [57]:
len(df_all[df_all['Характер работы'] == 'НАГ']['Скважина'].unique())

91

In [53]:
df_coords.shape

(346, 3)

In [61]:
len(set(list(df_all[df_all['Характер работы'] == 'НЕФ']['Скважина'].unique()) + list(df_all[df_all['Характер работы'] == 'НАГ']['Скважина'].unique())))

268

In [67]:
df_all[['Скважина', 'Характер работы', 'Закачка, м3']] \
                .groupby(['Скважина', 'Характер работы']) \
                .agg({'Закачка, м3' : 'count'})

                          Закачка, м3
Скважина Характер работы
101      НЕФ                       17
102      НАГ                       13
         НЕФ                        4
         НЕФ/НАГ                    1
103      НЕФ                       20
104      НЕФ                       21
105      НЕФ                       21
107      НЕФ                       21
109      НЕФ                       22
10Р      НЕФ                       69
10РБС    НЕФ                        3
110      НЕФ                       22
1167     НАГ                       14
         НЕФ                        9
         НЕФ/НАГ                    1
1199ГС   НЕФ                       30
1227     НЕФ                       23
1228     НЕФ                       20
1257ГС   НЕФ                       18
1258ГС   НЕФ                       24
1287     НАГ                        8
         НЕФ                       17
         НЕФ/НАГ                    1
1288     НАГ                       10
         НЕФ                       12
         НЕФ/НАГ                    1
1289     НАГ                       20
         НЕФ                       19
         НЕФ/НАГ                    2
1290     НЕФ                       41
...                               ...
2404     НЕФ/НАГ                    1
2405     НАГ                        6
         НЕФ                       16
         НЕФ/НАГ                    1
2435ГС   НЕФ                       20
2463     НАГ                       17
         НЕФ                        6
         НЕФ/НАГ                    1
2464     НЕФ                       19
2465     НАГ                       16
         НЕФ                        6
         НЕФ/НАГ                    1
2494ГС   НЕФ                       27
2495     НЕФ                       19
2523     НЕФ                       18
2524     НАГ                       12
         НЕФ                        8
         НЕФ/НАГ                    1
2553ГС   НЕФ                       19
2583     НАГ                       13
         НЕФ                        8
         НЕФ/НАГ                    1
25Р      НЕФ                       84
3Р       НЕФ                      102
6Р       НЕФ                      124
7Р       НЕФ                       49
8Р       НЕФ                       49
9        НАГ                       64
         НЕФ                        3
         НЕФ/НАГ                    1

[450 rows x 1 columns]

In [75]:
df_all[df_all['Обводненность'] == 0]['Характер работы']

Series([], Name: Характер работы, dtype: object)

In [76]:
df_all['Обводненность'].isnull().value_counts()

True     10164
False     5506
Name: Обводненность, dtype: int64

In [100]:
df_all[df_all['Дата'] <= '01.01.2019']

,Скважина,Дата,Характер работы,Состояние,"Время работы, ч","Нефть, т","Вода, т","Жидкость, т","Попутный газ, м3","Закачка, м3",...,Р пл,Р заб расчётное,Потери давления на трение,Р затр,Р уст,Закачка за месяц,Рпл,k,Р уст.1,Р заб
2843,101,01.01.2016,НЕФ,РАБ.,744,"452,34","399,01","851,35",18114,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2844,102,01.01.2016,НАГ,РАБ.,744,0,0,0,0,7461,...,247.4,408.889794,5.746146,137.0,173.0,7967.0,0.0,12.727842,173.0,0.000000
2845,103,01.01.2016,НЕФ,РАБ.,744,"613,71","333,62","947,33",24577,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2846,104,01.01.2016,НЕФ,РАБ.,744,"459,64","472,97","932,61",18407,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2847,105,01.01.2016,НЕФ,РАБ.,744,"906,52","297,41","1203,93",36303,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2848,107,01.01.2016,НЕФ,РАБ.,744,"568,84","237,69","806,53",22780,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2849,109,01.01.2016,НЕФ,РАБ.,744,"239,91","140,11","380,02",9607,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2850,10Р,01.01.2016,НЕФ,РАБ.,744,"296,56","331,56","628,12",11876,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2851,110,01.01.2016,НЕФ,РАБ.,744,"1236,06","772,89","2008,95",49500,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2852,1167,01.01.2016,НАГ,РАБ.,744,0,0,0,0,7495,...,185.0,411.513389,9.415461,50.0,176.0,7657.0,0.0,3.136531,176.0,425.646340
2853,1199ГС,01.01.2016,НЕФ,РАБ.,744,"54,63","366,15","420,78",2188,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2854,1227,01.01.2016,НЕФ,РАБ.,744,"740,51","448,97","1189,49",29655,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2855,1228,01.01.2016,НЕФ,РАБ.,744,"818,99","216,11","1035,11",32798,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2856,1257ГС,01.01.2016,НЕФ,РАБ.,744,"2960,07","1484,32","4444,39",118540,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2857,1258ГС,01.01.2016,НЕФ,РАБ.,735,"802,53","2801,2","3603,73",32138,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2858,1287,01.01.2016,НЕФ,РАБ.,744,"413,38","771,92","1185,3",16554,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2859,1288,01.01.2016,НЕФ,РАБ.,743,"758,35","418,6","1176,95",30369,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2860,1289,01.01.2016,НАГ,ОСВ ТГ,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2861,1290,01.01.2016,НЕФ,РАБ.,744,"799,72","285,81","1085,53",32026,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2862,12Р,01.01.2016,НЕФ,КОНС,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2863,1318ГС,01.01.2016,НЕФ,РАБ.,720,"1490,48","2161,74","3652,22",59688,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2864,1319ГС,01.01.2016,НЕФ,РАБ.,628,"1301,15","234,39","1535,54",52106,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2865,1347,01.01.2016,НЕФ,РАБ.,744,"309,54","228,37","537,91",12396,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2866,1348,01.01.2016,НЕФ,РАБ.,744,"562,86","543,07","1105,93",22540,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2867,1349,01.01.2016,НАГ,ОСВ ТГ,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2868,1350,01.01.2016,НАГ,РАБ.,744,0,0,0,0,9773,...,275.0,414.899756,3.091534,0.0,176.0,9300.0,0.0,7.850298,176.0,418.938140
2869,1379,01.01.2016,НЕФ,РАБ.,744,"921,18","624,47","1545,65",36890,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2870,1380ГС,01.01.2016,НЕФ,РАБ.,744,"1807,85","457,14","2264,99",72397,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2871,1381,01.01.2016,НАГ,РАБ.,744,0,0,0,0,6142,...,266.0,417.686745,4.966705,138.0,181.0,7347.0,0.0,13.017528,181.0,416.677235
2872,13ПО,01.01.2016,НЕФ,КОНС,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15327,1832,01.01.2009,НАГ,РАБ.,744,0,0,0,0,7276,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15328,1833,01.01.2009,НЕФ,ОСТ.,432,43,3,46,2815,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15329,1834,01.01.2009,НЕФ,ОСВ ТГ,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15330,1862,01.01.2009,НЕФ,РАБ.,744,704,388,1092,45751,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15331,1863,01.01.2009,НЕФ,РАБ.,744,728,243,971,47297,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15332,1892,01.01.2009,НЕФ,РАБ.,744,859,512,1371,55852,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15333,1893,01.01.2009,НЕФ,РАБ.,744,687,367,1054,44631,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15334,1894,01.01.2009,НЕФ,ОСТ.,552,94,5,99,6141,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15335,1895,01.01.2009,НЕФ,ОСВ ТГ,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15336,1923,01.01.2009,НЕФ,РАБ.,744,561,924,1485,36455,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15337,1924,01.01.2009,НЕФ,ОСВ ТГ,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15338,1954,01.01.2009,НАГ,РАБ.,744,0,0,0,0,4670,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15339,3Р,01.01.2009,НЕФ,РАБ.,744,985,135,1120,64002,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15340,6Р,01.01.2009,НЕФ,КОНС,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15538,1739,01.01.2008,НЕФ,РАБ.,744,1024,67,1091,63600,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15539,1740,01.01.2008,НЕФ,РАБ.,744,1630,63,1693,129800,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15540,1771,01.01.2008,НЕФ,РАБ.,744,1628,72,1700,101200,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15541,1801,01.01.2008,НЕФ,РАБ.,744,556,57,613,34600,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15542,1802,01.01.2008,НЕФ,РАБ.,744,1617,124,1741,100600,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15543,1830,01.01.2008,НЕФ,РАБ.,576,841,74,915,52300,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15544,1832,01.01.2008,НЕФ,РАБ.,744,862,142,1004,53600,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15545,1892,01.01.2008,НЕФ,РАБ.,744,1544,866,2410,95900,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15546,6Р,01.01.2008,НЕФ,РАБ.,744,390,55,445,24400,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15645,1739,01.01.2007,НЕФ,РАБ.,744,1035,49,1084,40300,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15646,1740,01.01.2007,НЕФ,РАБ.,744,769,9,778,30000,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15647,1801,01.01.2007,НЕФ,РАБ.,744,825,60,885,32200,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15648,1802,01.01.2007,НЕФ,ОСВ ТГ,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15649,1830,01.01.2007,НЕФ,ОСВ ПР ЛЕТ,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15650,1892,01.01.2007,НЕФ,ОСВ ПР ЛЕТ,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15651,6Р,01.01.2007,НЕФ,РАБ.,744,843,40,883,32900,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [102]:
pd.to_datetime(df_all['Дата'])

0       2016-01-12
1       2016-01-12
2       2016-01-12
3       2016-01-12
4       2016-01-12
5       2016-01-12
6       2016-01-12
7       2016-01-12
8       2016-01-12
9       2016-01-12
10      2016-01-12
11      2016-01-12
12      2016-01-12
13      2016-01-12
14      2016-01-12
15      2016-01-12
16      2016-01-12
17      2016-01-12
18      2016-01-12
19      2016-01-12
20      2016-01-12
21      2016-01-12
22      2016-01-12
23      2016-01-12
24      2016-01-12
25      2016-01-12
26      2016-01-12
27      2016-01-12
28      2016-01-12
29      2016-01-12
           ...
15640   2007-01-02
15641   2007-01-02
15642   2007-01-02
15643   2007-01-02
15644   2007-01-02
15645   2007-01-01
15646   2007-01-01
15647   2007-01-01
15648   2007-01-01
15649   2007-01-01
15650   2007-01-01
15651   2007-01-01
15652   2006-01-12
15653   2006-01-12
15654   2006-01-12
15655   2006-01-12
15656   2006-01-12
15657   2006-01-12
15658   2006-01-11
15659   2006-01-11
15660   2006-01-11
15661   2006-01-11
15662   2006-01-10
15663   2006-01-10
15664   2006-01-10
15665   2006-01-10
15666   2006-01-09
15667   2006-01-09
15668   2006-01-09
15669   2006-01-09
Name: Дата, Length: 15670, dtype: datetime64[ns]

In [104]:
720 / 24

30.0

In [125]:
df_all[df_all['Скважина'] == '1199ГС']['Дата ввода в эксплуатацию']

10     NaN
272    NaN
534    NaN
796    NaN
1056   NaN
1315   NaN
1574   NaN
1831   NaN
2088   NaN
2343   NaN
2598   NaN
2853   NaN
3108   NaN
3363   NaN
3618   NaN
3873   NaN
4128   NaN
4382   NaN
4635   NaN
4885   NaN
5131   NaN
5371   NaN
5608   NaN
5844   NaN
6074   NaN
6300   NaN
6524   NaN
6746   NaN
6967   NaN
7186   NaN
Name: Дата ввода в эксплуатацию, dtype: float64

In [121]:
df_all[(pd.to_datetime(df_all['Дата']) >= '2008-01-01') & (pd.to_datetime(df_all['Дата']) < '2009-01-01')]['Характер работы'].value_counts()

НЕФ        197
НАГ          6
НЕФ/НАГ      3
Name: Характер работы, dtype: int64

In [126]:
df_all[df_all['Дата'] == ]['Характер работы']

KeyError: "None of [Index(['01.12.2016', '01.12.2016', '01.12.2016', '01.12.2016', '01.12.2016',\n       '01.12.2016', '01.12.2016', '01.12.2016', '01.12.2016', '01.12.2016',\n       ...\n       '01.11.2006', '01.11.2006', '01.10.2006', '01.10.2006', '01.10.2006',\n       '01.10.2006', '01.09.2006', '01.09.2006', '01.09.2006', '01.09.2006'],\n      dtype='object', length=15670)] are in the [columns]"